[project]
name = "diarizacion_pipeline"
version = "0.1.0"
description = "Pipeline para transcribir videos de youtube, con predicción de turnos de habla e identificacion de hablantes conocidos"
authors = [
    {name = "Matías Miranda",email = "matias.miranda.c@ug.uchile.cl"}
]
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "aiohappyeyeballs",
    "aiohttp",
    "aiosignal",
    "alembic",
    "antlr4-python3-runtime",
    "asteroid-filterbanks",
    "attrs",
    "av",
    "certifi",
    "cffi",
    "charset-normalizer",
    "click",
    "colorama",
    "coloredlogs",
    "colorlog",
    "contourpy",
    "ctranslate2",
    "cycler",
    "defusedxml",
    "docopt",
    "einops",
    "faster-whisper",
    "filelock",
    "flatbuffers",
    "fonttools",
    "frozenlist",
    "fsspec",
    "greenlet",
    "huggingface-hub",
    "humanfriendly",
    "hyperpyyaml",
    "idna",
    "jinja2",
    "joblib",
    "julius",
    "kiwisolver",
    "lightning",
    "lightning-utilities",
    "mako",
    "markdown-it-py",
    "markupsafe",
    "matplotlib",
    "mdurl",
    "mpmath",
    "multidict",
    "networkx",
    "nltk",
    "numpy>=2.0,<2.1",
    "omegaconf",
    "onnxruntime",
    "optuna",
    "packaging",
    "pandas>=2.0,<2.3",
    "pillow",
    "primepy",
    "propcache",
    "protobuf",
    "pyannote-audio (==3.4.0)",
    "pyannote-core>=5.0",
    "pyannote-database>=5.0",
    "pyannote-metrics",
    "pyannote-pipeline",
    "pycparser",
    "pydub",
    "pygments",
    "pyparsing",
    "pyreadline3",
    "python-dateutil",
    "pytorch-lightning>=2.0,<2.6",
    "pytorch-metric-learning",
    "pytz",
    "pyyaml",
    "regex",
    "requests",
    "rich",
    "ruamel-yaml",
    "ruamel-yaml-clib",
    "safetensors",
    "scikit-learn",
    "scipy",
    "semver",
    "sentencepiece",
    "shellingham",
    "six",
    "sortedcontainers",
    "soundfile",
    "speechbrain",
    "sqlalchemy",
    "sympy",
    "tabulate",
    "tensorboardx",
    "threadpoolctl",
    "tokenizers>=0.14,<0.23",
    "torch",
    "torchvision>=0.17.2",
    "torch-audiomentations",
    "torch-pitch-shift",
    "torchaudio",
    "torchmetrics",
    "tqdm",
    "transformers>=4.37,<5.0",
    "typer",
    "typing-extensions",
    "tzdata",
    "urllib3",
    "whisperx @ git+https://github.com/m-bain/whisperX.git@b1c8ac7de62c5969343352f2d10a31ebe5a107fd",
    "yarl",
    "youtube-transcript-api",
    "yt-dlp"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"